### ISSUE TITLE
Rethinking calloop

### ISSUE THREAD

**Issue by vberger** [Smithay/calloop#12]
Over the last few days it appeared that `mio`'s behavior, and notably its focus on edge-triggered events, is an undesirable property. And as such, it may be relevant to drop it from being a calloop dependency. That would also mean focusing calloop on unix platforms, which I'm pretty confident it is only used on anyway.

On this process, I'm considering re-shaping calloop to, at the same time, fix the long-stating issue of ownership weirdness regarding the event sources. This issue is a design draft to gather feedback.

-------

Internally, calloop would contain a small abstraction around epoll and the appropriate equivalent for other platforms. This is a mostly-internal API, and only relevant for users that are going to implement their own event sources.

```rust
pub struct Poll { /* ... */ }

impl Poll {
    /// Register a new FD to the poll structure
    pub fn register(&mut self,
        fd: RawFd, /* the FD to register for polling */
        interest: Interest, /* Read / Write / Other... bitflag */
        mode: PollMode, /* oneshot, level, edge */
        token, Token /* opaque token to recognize the source */
    -> io::Result<()> {
        /* ... */
    }

    /// Update an FD registration
    pub fn update_registration(&mut self,
        fd: RawFd, i: Interest, m: PollMode, t: Token
    ) -> io::Result<()> {
        /* ... */
    }

    /// Remove a redigstration
    pub fn unregister(&mut self, fd: RawFD) -> io::Result<()> {
        /* ... */
    }
}
```

Now, comes the central trait of the crate: `Source`, representing an event source:

```rust
pub trait Source {
    /// The type of events this event source generates
    type Event;
    /// The return type expected from the callback closure, if the user
    /// needs to communicate back to the source.
    /// Set to () is not needed.
    type Ret;

    /// Process readiness of the source and translate it as events to the
    /// provided closure
    fn process_events<F>(&mut self, readiness: Readiness, callback: F) -> io::Result<()>
        where F: FnMut(Self::Event) -> Self::Ret;

    /// Make the source register itself to the `Poll`
    pub fn register(&mut self, &mut Poll, token: Token) -> io::Result<()> {
        /* ... */
    }

    /// Make the source update its registration
    pub fn update_registration(&mut self, &mut Poll, token: Token) -> io::Result<()> {
        /* ... */
    }

    /// Unregister the source
    pub fn unregister(&mut self, &mut Poll) -> io::Result<()> {
        /* ... */
    }
}
```

From this, the calloop user, to insert a new event source in the loop, needs to provide an implementation of the `Source` trait and a closure with matching signature. The loop takes ownership of both and provide a `SourceToken<S>` in exchange.

This `SourceToken<S>` can be usedto remove  the source from the `EventLoop`. Requires the same access as to insert a new source (so likely a `LoopToken`), the user is given the source `S` back. The closure is dropped.

Dropping the `SourceToken<S>` does nothing.

-------

Remaining questions:

- Is it worth introducing a `Waker` mechanism to remotely wake-up the event loop?

I'm thinking a special `Source` that just generates `()` events and can be remotely made ready should do that well, without requiring a specific `Waker` mechanism.

- This API draft allows a source to register more than one FD to the poll instance, however it does not allow the source to know which FD was made ready. Should we handle that?

A possibility would be to introduce a notion of sub-token (by splitting the u64 token into two u32s for example). An other would be to provide a `Multiplexer` source, which can aggregate several event sources by internally creating its own epoll instance and nesting them.

- Is it worth giving remote control of the source via the `SourceToken`? By allowing it to distantly disarm/rearm an event source for example, or destroy it (so that it is dropped) ?

**Comment by Drakulix** [comment]
I have some questions from a user perspective. I do not have a lot of insight into how epool works, so some of these questions might be already answered and I just do not get the concept.

- The `Pool`-api works with `RawFd`s. What happens if the actual owning type closes the `Fd`? Is this delivered to the event-listeners via any mechanism?
- What if my `Interest` is both `write` and `read`, but I need to handle both cases independently? Can I distinguish that?
- I think the callback should get all information possible: The fd, the interest, the event, if easily accessible by calloop.

**Comment by vberger** [comment]
>     * The `Pool`-api works with `RawFd`s. What happens if the actual owning type closes the `Fd`? Is this delivered to the event-listeners via any mechanism?

If the fd is closed, epoll will just stop generating events. The intent is that the `S: Source` inserted in the event loop should own the FD though.

>     * What if my `Interest` is both `write` and `read`, but I need to handle both cases independently? Can I distinguish that?

The `Readiness` argument provided to `process_events` will say if you have read readiness, write readiness, or both.

>     * I think the callback should get all information possible: The fd, the interest, the event, if easily accessible by calloop.

The `process_events` method should already have all that at hand. It's then its job te decide what is worth putting in the `Event` transmitted to the callback.
