### ISSUE TITLE
Storing registration token in structure

### ISSUE THREAD

**Issue by chiru091096** [Smithay/calloop#138]
Hi,
I want to store the [RegistrationToken](https://docs.rs/calloop/latest/calloop/struct.RegistrationToken.html) returned by [insert_source](https://docs.rs/calloop/latest/calloop/struct.LoopHandle.html#method.insert_source) in a structure as below example. What is the right way to initialize the token variable to a default value..

```
struct Test {
    token : RegistrationToken,
}

impl Test{
    new() ->Test {
       return Test {
           token : // how to initialize to dummy/default RegistrationToken value
       };
    }
}
```
Any help on this will be appreciated..

**Comment by elinorbgr** [comment]
Is there something preventing you from using an `Option<_>` ?

**Comment by chiru091096** [comment]
I'll try that, thanks
