### ISSUE TITLE
Better docs on how to integrate with futures.

### ISSUE THREAD

**Issue by cheako** [Smithay/calloop#32]
I'm not sure if I can even use adapt_io if I decide to use tokio.  It takes a file descriptor, but afaict EventSource don't have anything to do with those.

Likewise it's not clear how to call async functions using calloop, so I feel I'm going to eventually need to get EventSource playing nicely with tokio.

https://gitlab.com/cheako/hidcat/-/commit/86f0b34c1fef0922fea0112e077efc721d33e5f1

**Comment by vberger** [comment]
`adapt_io` is meant to provide a way to wake up powered by calloop, so *instead* of using Tokio or async_std.

Indeed, the docs are missing examples, in the meantime you can see an example of how to use adapt_io and the executor in this test : https://github.com/Smithay/calloop/blob/017e0cf5018d8778656cc6bbb0fbf8d6bde8c152/src/io.rs#L324

**Comment by vberger** [comment]
I believe this is now addressed by the [calloop tutorial](https://smithay.github.io/calloop/)

**Comment by cheako** [comment]
Currently, throwing a 404: https://smithay.github.io/calloop/chp03-00-async-await.html

Note: winit is also an interesting target, for embedded(ala xephyr or xnest) like compositors.

**Comment by vberger** [comment]
> Currently, throwing a 404: https://smithay.github.io/calloop/chp03-00-async-await.html

The broken links are now fixed.

> Note: winit is also an interesting target, for embedded(ala xephyr or xnest) like compositors.

I'm sorry I don't understand what you're suggesting here.
