### ISSUE TITLE
Struggling to integrate with socket-based code ⇒ API suggestions

### ISSUE THREAD

**Issue by detly** [Smithay/calloop#36]
I've been trying to integrate some (ZeroMQ) socket based code with Calloop, but I'm running up against lifetime errors around the same kind of pattern over and over again. Here's an example (without any ZeroMQ code at all):

```rust
use std::collections::VecDeque;

use calloop::generic::{Fd, Generic};
use calloop::signals::{Signal, Signals};
use calloop::{EventLoop, Interest, LoopHandle, LoopSignal, Mode, Readiness};

fn main() {
    // EventLoop and the handles it produces are parameterised by both a type
    // and lifetime. The lifetime is related to the lifetime of the stored
    // callbacks and sources. The definitions look like:
    //     pub struct EventLoop<'l, Data> {
    //         handle: LoopHandle<'l, Data>,
    //         ...
    let mut event_loop: EventLoop<LoopSignal> = EventLoop::try_new().unwrap();

    // Parameterised with same lifetime 'l as event_loop.
    let handle = event_loop.handle();

    // Exit on interrupt (for Ctrl-C when running in console) and terminate (for
    // OpenWrt's service control).
    const SIGNALS_TO_STOP_ON: &[Signal] = &[Signal::SIGINT, Signal::SIGTERM];

    let handle = event_loop.handle();

    handle
        .insert_source(
            Signals::new(SIGNALS_TO_STOP_ON).unwrap(),
            |event, _metadata, signaller: &mut LoopSignal| {
                println!("Signal received: {}", event.signal());
                signaller.stop();
            },
        )
        .unwrap();

    let mqueue = MessageQueue::new();
    mqueue.register(&handle);

    event_loop
        .run(None, &mut event_loop.get_signal(), |_| {})
        .expect("Could not run event loop");
}

struct Message<'f> {
    message: String,
    callback: Option<Box<dyn FnOnce() + 'f>>,
}

struct MessageQueue<'q> {
    queue: VecDeque<Message<'q>>,
}

impl<'q> MessageQueue<'q> {
    fn new() -> Self {
        MessageQueue {
            queue: VecDeque::new(),
        }
    }

    fn register<'l, D>(&self, handle: &LoopHandle<'l, D>) {
        let event_source = Generic::from_fd(0, Interest::READ, Mode::Edge);

        let callback = |_: Readiness, _: &mut Fd, _: &mut D| {
            self.on_socket_writeable();
            Ok(())
        };

        handle
            .insert_source(event_source, callback)
            .expect("Could not add control socket to event loop");
    }

    fn on_socket_writeable(&self) {
        while !self.queue.is_empty() {
            let _message = self.queue.pop_front().unwrap();
            // Real code sends message here.
        }
    }

    fn enqueue(&self, message: String) {
        self.queue.push_back(Message { message, callback: None });
        // Flush message queue manually.
        self.on_socket_writeable();
    }
}
```

Attempting to compile this results in the error:

```none
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> src/main.rs:61:24
   |
61 |           let callback = |_: Readiness, _: &mut Fd, _: &mut D| {
   |  ________________________^
62 | |             self.on_socket_writeable();
63 | |             Ok(())
64 | |         };
   | |_________^
   |
note: first, the lifetime cannot outlive the lifetime `'q` as defined on the impl at 51:6...
  --> src/main.rs:51:6
   |
51 | impl<'q> MessageQueue<'q> {
   |      ^^
note: ...so that the types are compatible
  --> src/main.rs:61:24
   |
61 |           let callback = |_: Readiness, _: &mut Fd, _: &mut D| {
   |  ________________________^
62 | |             self.on_socket_writeable();
63 | |             Ok(())
64 | |         };
   | |_________^
   = note: expected `(&&MessageQueue<'_>,)`
              found `(&&MessageQueue<'q>,)`
note: but, the lifetime must be valid for the lifetime `'l` as defined on the method body at 58:17...
  --> src/main.rs:58:17
   |
58 |     fn register<'l, D>(&self, handle: &LoopHandle<'l, D>) {
   |                 ^^
note: ...so that the types are compatible
  --> src/main.rs:67:14
   |
67 |             .insert_source(event_source, callback)
   |              ^^^^^^^^^^^^^
   = note: expected `&LoopHandle<'_, D>`
              found `&LoopHandle<'l, D>`
```

Basically, when the socket is writeable I want to send messages from the queue. However, I can't actually create the closure that does this because of lifetime issues that I don't quite understand. It doesn't *seem* like a circular problem on the face of it, since the `MessageQueue` that's captured by the closure in `register()` could happily outlive the event loop. Indeed, I tried to express this with:

```rust
    fn register<'l, D>(&self, handle: &LoopHandle<'l, D>)
    where 'q: 'l
```

But that results in:

```none
error[E0623]: lifetime mismatch
  --> src/main.rs:70:14
   |
59 |     fn register<'l, D>(&self, handle: &LoopHandle<'l, D>)
   |                        -----           -----------------
   |                        |
   |                        these two types are declared with different lifetimes...
...
70 |             .insert_source(event_source, callback)
   |              ^^^^^^^^^^^^^ ...but data from `self` flows into `handle` here
```

Anyway, the way I would break this stalemate in another language (eg. C + libuv) would be to add `self` (ie. the `MessageQueue`) as the data that gets passed to the callback instead of putting it in a closure. But by that I mean, the data that gets passed to *this specific callback*. Calloop only takes a single instance of callback data that gets passed to *every* function registered with the loop, so my queue structure would need to constrain the type of loop handle it gets eg. `register(&self, handle: &LoopHandle<'l, MessageQueue>)`. Then any code that wants to use this queue would need to construct a loop that only passes a `MessageQueue` to callbacks, so I'd have to incorporate extra callback data into *my* queue API, etc. etc.

So my suggestions, which I have not really thought the implications of through at all, are:
- let Calloop callbacks take per-registration data (perhaps by adding an extra type parameter to `LoopHandle` so that `event_loop.handle()` lets you register callbacks of a particular type?)
- Make Calloop callbacks also take a reference to the loop itself or a handle, so they can add timeouts etc. without having to create a closure over a loop handle

(If you do not or cannot implement this I will absolutely not take issue with that. They're just ideas I had while trying to puzzle this out.)

And if you can see anything I can do with my original code to break the stalemate, please let me know.

**Comment by vberger** [comment]
From what I get, your message queue stores pending messages in a buffer to flush them into the socket as it becomes writable. The intuitive approach I would consider to implement such a case in calloop would be to create a custom `EventSource`.

Calloop is build to be composable, meaning you can build new event sources by composing other ones. In your case, you could compose a `Generic<Fd>` to monitor your socket and a `Channel` to receive the events to be sent. It may look like something like that.

```rust
pub struct MessageQueue {
    socket: Generic<Fd>,
    incoming_messages: Channel<Message>,
    internal_buffer: VecDeque<Message>,
    // stand-in type to represent the rest of your relevant state
    mq_state: MqState,
}

const CHANNEL_READY: u32 = 1;
const SOCKET_READY: u32 = 2;

impl EventSource for MessageQueue {
    type Event = ();
    type Metadata = ();
    type Ret = ();

    fn process_events<F>(&mut self, readiness: Readiness, token: Token, callback: F) -> Result<()> {
        // we are invoked here if either the socket has become writable or the channel has become non-empty
        // if it is the channel, we empty it into our internal buffer
        let buffer = &mut self.internal_buffer;
        if token.sub_id == CHANNEL_READY {
            self.incoming_message.process_events(readiness, token, |message, _, _| {
                buffer.push_back(message);
            })?;
        }
        // if it is the socket, write as many messages as possible
        if token.sub_id = SOCKET_READY {
            let mq_state = &mut mq_state;
            self.socket.process_events(readiness, token, |_, socket, _| {
                while let Some(message) = buffer.pop_front() {
                    match mq_state.serialize_message(&mut socket, &message) {
                        Ok(()) => {},
                        Err(WouldBlock) => {
                            // put the message back in the buffer and bail
                            buffer.push_front(message);
                            break;
                        },
                        Err(e) => return Err(e),
                    }
                }
                Ok(())
            }
        }
    }

    fn register(&mut self, poll: &mut Poll, token: Token) -> std::io::Result<()> {
        self.socket.register(poll, Token { sub_id: SOCKET_READY, ..token })?;
        self.incoming_messages.register(poll, Token { sub_id: CHANNEL_READY, ..token })?;
        Ok(())
    }

    fn reregister(&mut self, poll: &mut Poll, token: Token) -> std::io::Result<()> {
        self.socket.reregister(poll, Token { sub_id: SOCKET_READY, ..token })?;
        self.incoming_messages.reregister(poll, Token { sub_id: CHANNEL_READY, ..token })?;
        Ok(())
    }

    fn unregister(&mut self, poll: &mut Poll) -> std::io::Result<()> {
        self.socket.unregister(poll)?;
        self.incoming_messages.unregister(poll)?;
        Ok(())
    }
}
```

So that example only covers the **writing** side of the coin. If your logic needs to also **read** from the socket and deserialize messages, you'd probably add the same logic, and forward the deserialized message to the provided user callback to your event source. That would mean you'd change `type Event;` to be `Message`, for example.

So, I hope this helps. The documentation of calloop clearly misses a general overview of "how to do what". :sweat_smile:

**Comment by detly** [comment]
That's fantastic, thanks! I'm asking because I'm putting together some example code for various async frameworks, so I will take this, and when I figure out the bigger picture I'll send a PR with some example code for documentation or the repo itself.

**Comment by detly** [comment]
Quick question on this — is there a reason other than simplicity or preference you use `u32` for the tokens instead of, say, a user defined enum?

**Comment by vberger** [comment]
It's mostly to have a low overhead, as the underlying system API only allows a `usize` as associated data to a registered file descriptor. Allowing an arbitrary type would require some overhead that does not seem worth it.

**Comment by detly** [comment]
One minor hiccup: your `Token { sub_id: Self::REQ_READY, ..token }` doesn't work because "field `id` of struct `Token` is private". It's fine to clone the passed in Token and modify the public `sub_id` field, however.

**Comment by vberger** [comment]
Ah, I was not aware that this didn't work. Indeed, in that case the correct way would be to clone the token and modify the field. Not as ergonomic though, probably worth adding a helper method.
