### ISSUE TITLE
Result<(), ()> (from Scheduler::schedule()) does not work well with other error handling

### ISSUE THREAD

**Issue by detly** [Smithay/calloop#43]
[`calloop::futures::Scheduler::schedule()`](https://docs.rs/calloop/0.8.0/calloop/futures/struct.Scheduler.html#method.schedule) returns a `Result<(), ()>`. Most approaches to error handling will not integrate easily with this because they are expecting the second type parameter of a `Result` to implement `std::error::Error`. For example, `anyhow` cannot easily wrap this result and needs an extra `map_err()` (or whatever) before it can even add context or extract a stack trace.

I notice that it's mostly due to the `.map_err(|_| ())` tacked on to the `send()` call. Is there a reason not to either pass up the error from `send()` or wrap it in a "real" error type?

**Comment by vberger** [comment]
> I notice that it's mostly due to the .map_err(|_| ()) tacked on to the send() call. Is there a reason not to either pass up the error from send() or wrap it in a "real" error type?

That's mostly lazyness on my side, from the fact that (as the docs describe), the only way this can fail is if the executor was destroyed. But I agree this should be a proper error type (as an unit struct).
