### ISSUE TITLE
Token sub-ID system does not allow more than one level of composition

### ISSUE THREAD

**Issue by detly** [Smithay/calloop#44]
Consider two custom event sources:

```rust
struct SourceOne {
    ping_one_a: calloop::ping::PingSource,
    ping_one_b: calloop::ping::PingSource,
}

struct SourceTwo {
    ping_two_a: calloop::ping::PingSource,
    ping_two_b: calloop::ping::PingSource,
}
```

Following the composition technique suggested in #36, you might create either of these with their own token sub-IDs:

```rust
impl SourceOne {
    const ID_A: u32 = 1;
    const ID_B: u32 = 2;
}

impl SourceTwo {
    const ID_A: u32 = 1;
    const ID_B: u32 = 2;
}
```

This works fine, you can use the `ID_*` sub-IDs to differentiate the ping sources in either custom event source.

Now consider what happens if you want to create an event source that uses either or both of those. Where should an API user start *their* token sub-IDs?

I am making the assumption here that any token sub-IDs used by a custom source are implementation details. If that's the case, then a writer of a new source `SourceThree` that contains `SourceOne` plus another source would not know to start their sub-IDs at 3 instead of 1. If they don't, then they will collide: they only get the one `token` in `register()`, and so in `process_events()` there is no way to distinguish eg. `SourceOne::ping_one_b` from whichever `SourceThree` source has sub-ID 2.

Even if we don't make that assumption, there's still a problem. If `SourceThree` wants to combine *both* `SourceOne` and `SourceTwo`, the sub-IDs will always collide, and `SourceThree::process_events()` will have no way to distinguish whether a given event was due to `SourceOne::ping_one_a` or `SourceTwo::ping_two_a`. So even if sub-IDs are considered part of the API of an event source, any given event source needs to know about every other kind of event source, *even any created and published by 3rd parties*, to avoid collisions.

Or have I missed something?

**Comment by vberger** [comment]
Ah, indeed, it does not really scale beyond a single level of composition of elementary sources. We'll probably need dynamic assignation of sub-id's for this to work correctly.

I'm thinking of something like:

- Changing the `register`/`reregister` methods to instead take `&mut TokenFactory` with a `next_token()` method, that would produce a new unique token.
- The `sub_id` field would be private again, and sources would just compare the provided token in `process_events` to the one(s) they have been given at registration time to know if this invocation was actually targeted at them. If not, `process_events` should do nothing.
- To compose source, the higher-level source would just unconditionally invoke the `process_events` methods of its sub-source with the token given as argument, and each sub-source would then decide if it actually has something to do or not.

How does that sound?

**Comment by detly** [comment]
This is more or less what I was thinking. But I wonder if we can make it a little more static/type system supported?

**Comment by vberger** [comment]
Do you have some ideas about how to achieve that? I settled for dynamic because I couldn't think of any way to achieve this statically.

Dynamically achieving it also opens the way for dynamic storing of sources as `Box<dyn EventSource>` and such, but I'm not quite sure if/how that is actually useful.

**Comment by detly** [comment]
> Do you have some ideas about how to achieve that? I settled for dynamic because I couldn't think of any way to achieve this statically.

Sorry, I missed this. But my answer is: eh. I had it in my head that this was more of a problem than it actually is, but our discussions elsewhere made me realise it wasn't important. The dynamic generation is a great solution.
