### ISSUE TITLE
Ownership issues with LoopHandle::insert_source

### ISSUE THREAD

**Issue by tonyxty** [Smithay/calloop#7]
`LoopHandle::insert_source` takes ownership of `E` and moves it to the return value.  This behavior is undocumented and might be confusing.  A minimal example:

```rust
use calloop::EventLoop;
use calloop::signals::{Signal, Signals};
use std::process;

fn main() {
    println!("pid: {}", process::id());
    let mut event_loop = EventLoop::<()>::new().unwrap();
    let handle = event_loop.handle();
    let signals = Signals::new(&[Signal::SIGUSR1]).unwrap();
    handle.insert_source(signals, |_, _| {
        println!("SIGUSR1");
    }).unwrap();
    loop {
        event_loop.dispatch(None, &mut ());
    }
}
```

Expected behavior: Prints "SIGUSR1" upon receiving SIGUSR1.
Actual behavior: The process terminates at SIGUSR1.  Since `signals` has been moved to the return value of `insert_source` and dropped, the signals are unmasked.

The fix here is to bind the return value of `insert_source`.  I think this is rather counter-intuitive.  Perhaps `insert_source` should borrow the source instead?

**Comment by vberger** [comment]
Indeed, you are expected to keep the returned `Source` alive, as described [in its documentation](https://docs.rs/calloop/0.4.4/calloop/struct.Source.html).

The reason behind this is that the initial use-case (wayland-server) needs to regularly insert and remove sources from the loop, and making `insert_source` only borrow the resource would risk stuff like having it dropped without being cleanly removed from the event loop, which I think may risk leaking resources or maybe behaviour that is not well defined.

If you know you'll never need to access the `Source` again and leave it registered until the end of your program, you can still `std::mem::forget(..)` it.

**Comment by tonyxty** [comment]
If in the struct `Source` we make `source` a reference with a lifetime specifier, the compiler should be able to ensure that the `EventSource` outlives the `Source`.  Perhaps something like
```rust
pub struct Source<'a, E: EventSource> {
    pub(crate) source: &'a mut E,
    pub(crate) poll: Rc<Poll>,
    pub(crate) list: Rc<RefCell<ErasedList>>,
    pub(crate) token: Token,
}
```
might work?

This breaks current code (need to add mutable borrow) and does not gain much though.  For now maybe repeating the documentation in `insert_source` would help?

**Comment by vberger** [comment]
I could work, but I'm afraid it'd make the crate incredibly tedious to use for complex workflows (like `wayland-server` does, dynamically inserting and removing sources), so I don't think this is a direction I'd be willing to pursue...

Improving the documentation is always a good idea though!
