### ISSUE TITLE
"Transient" source wrapper (includes channel CPU spike issue)

### ISSUE THREAD

**Issue by detly** [Smithay/calloop#78]
I accidentally triggered a 100% CPU spike in my code, and managed to reduce it to this situation:

```rust
use calloop::{
    channel::{channel, Channel},
    signals::{Signal, Signals},
    EventLoop, EventSource, LoopSignal, PostAction,
};

struct HasChannel(Channel<()>);

impl HasChannel {
    fn new() -> Self {
        Self(channel().1)
    }
}

impl EventSource for HasChannel {
    type Event = calloop::channel::Event<()>;
    type Metadata = ();
    type Ret = ();

    fn process_events<F>(
        &mut self,
        readiness: calloop::Readiness,
        token: calloop::Token,
        callback: F,
    ) -> std::io::Result<calloop::PostAction>
    where
        F: FnMut(Self::Event, &mut Self::Metadata) -> Self::Ret,
    {
        self.0.process_events(readiness, token, callback)?;
        Ok(PostAction::Continue)
    }

    fn register(
        &mut self,
        poll: &mut calloop::Poll,
        token_factory: &mut calloop::TokenFactory,
    ) -> std::io::Result<()> {
        self.0.register(poll, token_factory)
    }

    fn reregister(
        &mut self,
        poll: &mut calloop::Poll,
        token_factory: &mut calloop::TokenFactory,
    ) -> std::io::Result<()> {
        self.0.reregister(poll, token_factory)
    }

    fn unregister(&mut self, poll: &mut calloop::Poll) -> std::io::Result<()> {
        self.0.unregister(poll)
    }
}

fn main() -> std::io::Result<()> {
    // Event loop initialisation.
    let mut event_loop: EventLoop<LoopSignal> = EventLoop::try_new()?;

    const SIGNALS_TO_STOP_ON: &[Signal] = &[Signal::SIGINT, Signal::SIGTERM];

    let handle = event_loop.handle();

    let mut signaller = event_loop.get_signal();

    handle.insert_source(
        Signals::new(SIGNALS_TO_STOP_ON)?,
        |_, _metadata, signaller| signaller.stop(),
    )?;

    handle.insert_source(HasChannel::new(), |_, _, _| {})?;

    event_loop.run(None, &mut signaller, |_| {})?;

    Ok(())
}
```

(This can run as a `main.rs` with only `calloop = "0.9.3"` as a dependency.)

Running this you should see the CPU hit 100% on one core. **It's arguably not a bug!** What's happening is that the channel sending end is dropped, so the `process_events()` method on the channel returns `PostAction::Remove`. The `process_events()` method on `HasChannel` erroneously ignored this return value; what it should do is check for it, and return a `PostAction::Reregister` instead of `PostAction::Continue`. Then in the `reregister()` method, it should unregister the channel while keeping itself registered (if there's any reason to).

You could make a case that the channel should be coded to try to avoid spiking the CPU like this even if it's not unregistered, but I couldn't see an easy way to do that (I didn't look very hard though). 

On issue #77 you mentioned maybe having a way for such sources to remove themselves from the loop. The problem is that "top level" sources can be removed by the code in `loop_logic` itself, but "child" sources can't. Their `PostAction` return value is only seen by another event source, not the loop logic itself. There are other strategies though. Here's a summary of what I can think of, maybe you have other ideas:

1. A wrapper type. I actually have one that I could either add to Calloop itself or publish as a crate. It's called `TransientSource`, the API and struct looks like this:

    ```rust
    //! Wrapper for a transient Calloop event source. If you have high level event
    //! source that you expect to remain in the event loop indefinitely, and another
    //! event source nested inside that one that you expect to require removal or
    //! disabling from time to time, this module can handle it for you.

    /// A [`TransientSource`] wraps a Calloop event source and manages its
    /// registration. A user of this type only needs to perform the usual Calloop
    /// calls (`process_events()` and `*register()`) and the return value of
    /// [`process_events()`].
    ///
    /// Rather than needing to check for the full set of [`calloop::PostAction`]
    /// values returned from [`process_events()`], you can just check for `Continue`
    /// or `Reregister` and pass that back out through your own `process_events()`
    /// implementation. In your registration functions, you then only need to call
    /// the same function on this type ie. `register()` inside `register()` etc.
    pub enum TransientSource<T> {
        Keep(Box<T>),
        Register(Box<T>),
        Disable(Box<T>),
        Remove(Box<T>),
        None,
    }
    ```

    Then in my `HasChannel` source you'd just have `TransientSource<Channel>` instead of `Channel`. If you like that idea I can open a PR with it.

2. This works even better if you have a simple combinator/operator for the `PostAction` values so that eg. `PostAction::Continue ⊕ PostAction::Remove => PostAction::Reregister` or something like that. I haven't fully thought through the truth table/edge cases for such an operator, so you'd need to review it carefully.

3. Alternatively to 1&2, you could have a kind of shim layer in between parent and child event sources, such that a parent event source would call this shim code, which would then call `process_events()` on the child and handle the return value, removing it if necessary. This gets complicated though, because you'd then also want to handle the `(re|un)register()` methods, and the lifetimes might get tricky.

4. Ditch that altogether, flatten the recursive composition structure, and have a less direct way for event sources to have child sources. Maybe based on the tokens that already exist? This is the option I've thought about the least, TBH.

Let me know if you have other thoughts, because I basically picked the `TransientSource` approach and ran with it due to time constraints. It works well though!

**Comment by vberger** [comment]
Hmm, there are a lot of interesting ideas here, and I like the idea of adding some helper machinery to make the composition of sources easier.

The main part that is blurry in my mind is that your proposal is quite focused on having a combination of sources which may mostly continue working "as is" after one or more underlying sources have been disabled. I'm wondering how common an use it maybe. My initial intuition would have been that if you expect that some underlying sources might be disabled during the lifetime of your main source, it may actually often require some special processing from your side to handle that?

Though indeed, as I'm writing this, a source that basically aggregates events from multiple underlying sources could often need to "just continue" after one of those underlying sources have stopped emitting events... :thinking:

**Comment by detly** [comment]
> My initial intuition would have been that if you expect that some underlying sources might be disabled during the lifetime of your main source, it may actually often require some special processing from your side to handle that?

It definitely does, *but* there is also a lot of code in common between the sources I've written that do this. Specifically — having an owned-but-droppable source (eg. an `Option` or `Box`), making sure you do the right thing in a `reregister()` call after seeing a `PostAction::Remove` return value in `process_events()`, etc. That stuff is easy to pull out and test to save people from some unobvious errors.

The two examples I have for this are:

- ZeroMQ. This is a perfect example of *"a source that basically aggregates events from multiple underlying sources could often need to "just continue" after one of those underlying sources have stopped emitting events"*. Certain ZeroMQ sources simply don't need to send messages, just receive, so it makes sense for a caller to close the channel to prevent misuse. At this point the channel source returns `PostAction::Remove`, and the code to handle that is identical to the code needed for the next example. But the machinery in the ZeroMQ source itself just goes on like nothing happened - it'll still receive messages and fire the callback when it does, and it will still call `process_events()` on the `TransientSource` wrapped channel and not care that nothing ever happens with it.

- Subprocesses. Currently this uses `async-process` because my embedded target doesn't support `pidfd`, but eventually I plan to support both. This is a good example of *not* *"having a combination of sources which may mostly continue working "as is" after one or more underlying sources have been disabled"* — there is definitely more cleanup and integration code to follow a subprocess ending, but the part of that that's just removing the async scheduler/executor is exactly the same as removing the closed channel in the ZeroMQ source.

**Comment by detly** [comment]
I was slightly wrong about the subprocess thing, the `TransientSource` is also used for handling a channel that's closed; the async scheduler/executor is kept and re-used.

**Comment by detly** [comment]
Two more examples:

- In application code (that I can't release), I have `TransientSource` wrappers around more complex event sources that listen to the output of subprocesses. It's the easiest way to prevent file descriptor leaks in such sources.
- USB integration. Each device on the bus requires a new `Generic` source, which can come and go when devices are added or removed.

**Comment by vberger** [comment]
I see, that makes a lot of sense, and the adapter looks pretty clean. If there are multiple such sources, that would indeed be useful to have a `BitOr` implementation for `PostAction`. I think we can get that into calloop, that seems like a useful addition. :+1:
