### ISSUE TITLE
Investigate non-deterministic timer test failure on macos

### ISSUE THREAD

**Issue by vberger** [Smithay/calloop#84]
The current timer implementation on macos randomly fails the CI in a non-deterministic way. It'd be nice if someone with access to a macos computer could investigate it.

**Comment by i509VCB** [comment]
Interestingly this does not happen on an m1 mac mini, not sure why the CI environment keeps having these issues.

**Comment by vberger** [comment]
Currently yes

**Comment by detly** [comment]
> Interestingly this does not happen on an m1 mac mini, not sure why the CI environment keeps having these issues.

It's probably due to speed or number of cores, I had a similar dog of a time trying to figure out the story behind #79 until I deliberately slowed it down by running under Tarpaulin.

**Comment by detly** [comment]
Do you need to re-enable CI on OS X now that #89 is merged?

**Comment by vberger** [comment]
I don't think is was ever disabled...?

**Comment by detly** [comment]
I thought it was removed as part of 2c40aec276ef76d96cfa9af4032d1d962d78b254. There's only a `macos-latest` entry for the coverage job. Same if I look under the [actions](https://github.com/Smithay/calloop/actions/runs/2063443574).

**Comment by vberger** [comment]
Ah yeah, I reorganized the CI when changing the coverage system. You think we need for CI runs for macos?

**Comment by detly** [comment]
Not if we have *one*, I just couldn't find it in the GH actions.

**Comment by vberger** [comment]
Not sure I understand your point, coverage jobs run the test suite and fail if the test suite fails, so I suppose all is good...?

**Comment by detly** [comment]
Yes, exactly, it's all fine.
