### ISSUE TITLE
Enhancement: PostAction combinator

### ISSUE THREAD

**Issue by detly** [Smithay/calloop#87]
In #78 I mentioned a possible "combinator" for Calloop's `PostAction` enum, to make managing child sources a bit smoother. It's possible this is not as necessary now that `TransientSource` is a part of the library, but I figured I'd propose something to gauge interest and flesh out the details. I keep calling it a combinator, but you suggested bit-or (`|`) in that thread. I'm only keeping it open in case it turns out to not quite work the way we expect.

Notes:

- This is for combining `PostAction`s from child sources at the same level, not for combining a child action with the parent's
- I'm assuming it's symmetric, I think it would be quite surprising if it weren't (hence the empty lower left side)
- the parent source might want to do something different, this operator is mainly for "if I had no logic apart from capturing events from my child sources, what would I need to return to be correct"

Here's a "truth" table for `PostAction`:

| op         | Continue | Reregister | Disable    | Remove     |
|------------|----------|------------|------------|------------|
| Continue   | Continue | Reregister | Reregister | Reregister |
| Reregister |          | Reregister | Reregister | Reregister |
| Disable    |          |            | :question: | Disable?   |
| Remove     |          |            |            | :question: |

The reason I'm unsure about the diagonals is because of that last bullet point above. If a parent has several child sources and they ALL want to be disabled, should the operator return `Disabled` and let the parent source decide whether it, itself, should be disabled or reregistered? Does the disabled status need to "propagate" downwards through the tree?

**Comment by vberger** [comment]
> The reason I'm unsure about the diagonals is because of that last bullet point above. If a parent has several child sources and they ALL want to be disabled, should the operator return Disabled and let the parent source decide whether it, itself, should be disabled or reregistered? Does the disabled status need to "propagate" downwards through the tree?

Is there any reason for this to not be the case?

**Comment by detly** [comment]
Thinking about it, no, it makes sense to have the operator simply do:

- `X` if `X == Y`
- `Reregister` if `X != Y`
