### ISSUE TITLE
Use OS-based sources for timer when possible

### ISSUE THREAD

**Issue by vberger** [Smithay/calloop#9]
This is at least possible on linux by using a timerfd. I don't know about other platforms.

This would allow use to only spawn a timer thread when needed.

**Comment by NBonaparte** [comment]
Not sure if you've seen this already, but [tokio-os-timer](https://github.com/jonhoo/tokio-os-timer) does this for tokio. It uses kqueue for macOS/BSD, but apparently Windows doesn't have timers for IOCP (https://github.com/jonhoo/tokio-os-timer/issues/9).

**Comment by i509VCB** [comment]
It may be worth looking further into this I guess since macOS is currently a bit spotty on CI with the thread executor based timer
